### ISSUE TITLE
Upgrade base image to sid

### ISSUE THREAD

**Issue by Xyene** [DMOJ/runtimes-docker#19]
It mostly just works. Outstanding errors:

* [x] OCaml
```
Auto-configuring OCAML:  Failed self-test
  Attempted:
    ocaml: /usr/bin/ocamlopt
  Errors:
    Traceback (most recent call last):
      File "/judge/dmoj/executors/base_executor.py", line 136, in run_self_test
        executor = cls(cls.test_name, utf8bytes(cls.test_program))
      File "/judge/dmoj/executors/compiled_executor.py", line 64, in __call__
        obj.compile()
      File "/judge/dmoj/executors/compiled_executor.py", line 248, in compile
        self.handle_compile_error(output)
      File "/judge/dmoj/executors/compiled_executor.py", line 233, in handle_compile_error
        raise CompileError(output)
    dmoj.error.CompileError: File "/tmp/tmpl80n39pv/self_test.ml", line 1:
    Error: Cannot find file nums.cmxa
```
* [x] Steel Bank Common Lisp
```
Auto-configuring SBCL:   Denied access via syscall openat: /dev/tty

Error: unbound variable: read-lines

	Call history:

	/tmp/tmp9ircrd5n/self_test.scm:1: read-lines	 	<--
ERROR: ld.so: object '/tmp/tmp2_12wxrq/setbufsize.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Using /usr/bin/sbcl
```
* [x] Chicken Scheme (upgrading from 4.13 to 5.2 has breaking changes)
```
Auto-configuring SCM:    Failed self-test
  Attempted:
    chicken-csc: /usr/bin/chicken-csc
  Errors:
    Got unexpected stdout output:
    
```
* [x] Ruby
```
Auto-configuring RUBY2:  Failed to find "ruby2"
```

**Comment by Xyene** [comment]
This is done.
